networks:
  automation-net:


services:
  video-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-engine
    restart: unless-stopped
    expose:
      - "8000"
    volumes:
      - video_tmp_data:/tmp/video_engine
    networks:
      - automation-net

volumes:
  video_tmp_data: